### ISSUE TITLE
Missing the word, "zoo"

### ISSUE THREAD

**Issue by mikegwhit** [matthewreagan/WebstersEnglishDictionary#1]

**Comment by matthewreagan** [comment]
Thanks for catching. This repo is mainly to provide the parsing tool, the dictionary itself is maintained and provided by the Gutenberg project and can be easily modified or updated (the JSON files etc. can then be recreated by running the CLI tool), so modifying or updating the dictionary for missing words isn't within the scope of this project. Going to close.
