### ISSUE TITLE
downloading dictionary.json prints contents on browser window.

### ISSUE THREAD

**Issue by bellarmine69** [matthewreagan/WebstersEnglishDictionary#6]
First, I should say that I am relatively new to programming.  

I'm working on an anagram program now and need an english dictionary.  I clicked on the download button to download dictionary.json and was expecting a prompt to ask me where I wanted to save it.  instead, it printed the entire contents of the dictionary (which is big!) in a new window in Chrome.  

Is there a way to just download the file to my computer instead of printing its contents on a new browser page?  

If i did something wrong, would love to know what.  

Thanks,

**Comment by matthewreagan** [comment]
Hi @bellarmine69, if you navigate to the main page for the repo on GitHub, up towards to the top you'll see a green button that says 'Code', if you click that there will be an option to 'Download ZIP'. From there you can choose the save location. All of the files for the project will be downloaded, but you can navigate to whichever dictionary JSON you needed and use the file however you want.

**Comment by bellarmine69** [comment]
thanks so much.  it might have been a naive question but I am still in my
early days!

thanks again.
