### ISSUE TITLE
Invalid / Missing definitions

### ISSUE THREAD

**Issue by markmsmith** [matthewreagan/WebstersEnglishDictionary#9]
I'm not sure if this is a fault with the source material or how it was parsed in to the json format, but there appears to be some nonsensical definitions, for example for hyphen:

`-`:

> (a) Establishment in life, in business, condition, etc.; ordination or installation as pastor. Every man living has a design in his head upon wealth power, or settlement in the world. L'Estrange. (b) The act of peopling, or state of being peopled; act of planting, as a colony; colonization; occupation by settlers; as, the settlement of a new country. (c) The act or process of adjusting or determining; composure of doubts or differences; pacification; liquidation of accounts; arrangement; adjustment; as, settlement of a controversy, of accounts, etc. (d) Bestowal, or giving possession, under legal sanction; the act of giving or conferring anything in a formal and permanent manner. My flocks, my fields, my woods, my pastures take, With settlement as good as law can make. Dryden. (e) (Law)  A disposition of property for the benefit of some person or persons, usually through the medium of trustees, and for the benefit of a wife, children, or other relatives; jointure granted to a wife, or the act of granting it. 2. That which settles, or is settled, established, or fixed. Specifically: -- (a) Matter that subsides; settlings; sediment; lees; dregs. [Obs.] Fuller's earth left a thick settlement. Mortimer. (b) A colony newly established; a place or region newly settled; as, settlement in the West. (c) That which is bestowed formally and permanently; the sum secured to a person; especially, a jointure made to a woman at her marriage; also, in the United States, a sum of money or other property formerly granted to a pastor in additional to his salary. 3. (Arch.) (a) The gradual sinking of a building, whether by the yielding of the ground under the foundation, or by the compression of the joints or the material. (b) pl.  Fractures or dislocations caused by settlement. 4. (Law)  A settled place of abode; residence; a right growing out of residence; legal residence or establishment of a person in a particular parish or town, which entitles him to maintenance if a pauper, and subjects the parish or town to his support. Blackstone. Bouvier. Act of settlement (Eng. Hist.), the statute of 12 and 13 William III, by which the crown was limited to the present reigning house (the house of Hanover). Blackstone.

or double hyphen:
`--`:
> (a) Denoting relation to some thing or person that is superior, weighs upon, oppresses, bows down, governs, directs, influences powerfully, or the like, in a relation of subjection, subordination, obligation, liability, or the like; as, to travel under a heavy load; to live under extreme oppression; to have fortitude under the evils of life; to have patience under pain, or under misfortunes; to behave like a Christian under reproaches and injuries; under the pains and penalties of the law; the condition under which one enters upon an office; under the necessity of obeying the laws; under vows of chastity. Both Jews and Gentiles . . . are all under sin. Rom. iii. 9. That led the embattled seraphim to war Under thy conduct. Milton. Who have their provand Only for bearing burdens, and sore blows For sinking under them. Shak. (b) Denoting relation to something that exceeds in rank or degree, in number, size, weight, age, or the like; in a relation of the less to the greater, of inferiority, or of falling short. Three sons he dying left under age. Spenser. Medicines take effect sometimes under, and sometimes above, the natural proportion of their virtue. Hooker. There are several hundred parishes in England under twenty pounds a year. Swift. It was too great an honor for any man under a duke. Addison. Note: Hence, it sometimes means at, with, or for, less than; as, he would not sell the horse under sixty dollars. Several young men could never leave the pulpit under half a dozen conceits. Swift. (c) Denoting relation to something that comprehends or includes, that represents or designates, that furnishes a cover, pretext, pretense, or the like; as, he betrayed him under the guise of friendship; Morpheus is represented under the figure of a boy asleep. A crew who, under names of old renown . . . abused Fanatic Egypt. Milton. Mr. Duke may be mentioned under the double capacity of a poet and a divine. Felton. Under this head may come in the several contests and wars betwixt popes and the secular princes. C. Leslie. (d) Less specifically, denoting the relation of being subject, of undergoing regard, treatment, or the like; as, a bill under discussion. Abject and lost, lay these, covering the flood, Under amazement of their hideous change. Milton. Under arms. (Mil.) (a) Drawn up fully armed and equipped. (b) Enrolled for military service; as, the state has a million men under arms. -- Under canvas. (a) (Naut.) Moved or propelled by sails; -- said of any vessel with her sail set, but especially of a steamer using her sails only, as distinguished from one under steam. Under steam and canvas signifies that a vessel is using both means of propulsion. (b) (Mil.) Provided with, or sheltered in, tents. -- Under fire, exposed to an enemy's fire; taking part in a battle or general engagement. -- Under foot. See under Foot, n. -- Under ground, below the surface of the ground. -- Under one's signature, with one's signature or name subscribed; attested or confirmed by one's signature. Cf. the second Note under Over, prep. -- Under sail. (Naut.) (a) With anchor up, and under the influence of sails; moved by sails; in motion. (b) With sails set, though the anchor is down. (c) Same as Under canvas (a), above. Totten. -- Under sentence, having had one's sentence pronounced. -- Under the breath, with low voice; very softly. -- Under the lee (Naut.), to the leeward; as, under the lee of the land. -- Under the rose. See under Rose, n. -- Under water, below the surface of the water. -- Under way, or Under weigh (Naut.), in a condition to make progress; having started.

There also appears to be a definition for every single letter except for `t`, which each have the form "The i-th letter of the English alphabet ...".  I'm not sure why `t` was the only one that merited exclusion :)

Just thought you'd appreciate a heads-up on these, as they seemed a bit strange.

**Comment by matthewreagan** [comment]
Hi @markmsmith, this repo is for a JSON parsing tool for processing the free English dictionary provided by the [Gutenberg project](https://www.gutenberg.org/). The included dictionary was just added as a convenience and it has very likely (or at least hopefully) been corrected/updated since this repo was created.

You might check the Gutenberg website for the latest version. I will update the repo README to provide additional clarity around this. Thanks.
